package kr.kirk.euler.p000;

/*

삼각수, 오각수, 육각수는 아래 식으로 구할 수 있습니다.
삼각수 	  	Tn = n (n + 1) / 2 	  	1, 3, 6, 10, 15, ...
오각수 	  	Pn = n (3n − 1) / 2 	  	1, 5, 12, 22, 35, ...
육각수 	  	Hn = n (2n − 1) 	  	1, 6, 15, 28, 45, ...

여기서 T285 = P165 = H143 = 40755 가 됩니다.

오각수와 육각수도 되는, 그 다음으로 큰 삼각수를 구하세요.e pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

public class Problem045 {

	public static void main(String[] args) {
		System.out.println(solution());
	}

	private static long solution() {

		for ( long i=144;;i++) {
			long pH = i * (2*i - 1);
			System.out.println(i + " : " +pH);
			if ( isPentagonal(pH)) {
				return pH;
			}
		}
	}

	private static boolean isPentagonal(long i) {
		long a = (1 + (long)Math.sqrt(24*i + 1))/6;
		if (a * ( 3*a -1 ) /2 == i) return true;		
		return false;
	}
}